#!/usr/bin/env -S bash\_--login\_-c\_"eval\_\"\$(sed\_-n\_/^\$(printf\_\\\\x23)!-/s/\$(printf\_\\\\x23)!-//p\_\$0)\""
#!- for arg in "$@"; do
#!-   if [ "$arg" == "-h" ]; then
#!-     >&2 echo usage: dmux +[+\|session-name]
#!-   fi
#!- done
#!- if [ "$1" == + ]; then
#!-   tmux -L=dmux list-sessions 2>/dev/null || >&2 echo no sessions
#!-   exit
#!- elif [ "${1:0:1}" == + ]; then
#!-   if [ "${1:0}" == ++ ]; then
#!-     exec tmux -L=dmux -f $0 attach
#!-   fi
#!-   exec tmux -L=dmux -f $0 new-session -A -t "${1:1}"
#!- fi
#!- exec tmux -L=dmux -f $0 "$@"


########
# TODO: Plugin to rearrange with stack/chain/span (M-:) potentially control mode.
# TODO: Improve scrollback with bind for loading history in a familiar editor

set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm*:Tc"
set-environment -g COLORTERM "truecolor"
set -g escape-time 0
set -g status off
set -g pane-border-lines double
set -g aggressive-resize on
set -g pane-border-style bg=default,fg=brightblack
set -g pane-active-border-style bg=default,fg=brightblue
set -g message-style bg=color238,fg=brightyellow
set -g base-index 1
set -g renumber-windows on
set -g extended-keys on
set -g focus-events on
set -g mouse on
unbind -na

set-hook -g session-created {display "Alt+? for help"}
bind -n M-? display-popup -w38 -h15 'echo "\
Alt +
  ⎵     launch new <SPACE>
  ⇥     <TAB> swap panes
  ◅◊▻   <NAV> across panes (or ⦺⇕)
  ⦺⊹    <DRAG> borders to resize
  ⏎     <ENTER> or leave fullscreen
  ⌫     <BACKSPACE> close the pane
  :     span a new space at top
  ,.    desk jump (or ⇧+⦺⇕ or 1-9)
  <>    yank pane across desks
  ()    lift desk to new position
  ~     switch sessions
  esc   <ESCAPE> to disconnect"'

# Scrollback
bind -n WheelUpPane if-shell -F "#{||:#{pane_in_mode},#{mouse_any_flag}}" \
	{ send-keys -M } { copy-mode -e }

# Session management
set -g @sessions "\
#[fg=brightwhite,bg=red]\
 #{session_name} \
#[fg=black,bg=black]\
#{E:##{p#{#{e|-:#{window_width},#{w:session_name}}:#}}}\
"
bind -n M-~ {switch-client -n ; display "#{E:@sessions}"}
bind -n M-Escape detach-client

# Desk(window) management
set -g @desks "\
#[fg=brightwhite,bg=red]\
#{window_index}\
 \
#{?#{<:#{session_windows},1},_,#{?#{==:#{window_index},1},▀,￭}}\
#{?#{<:#{session_windows},2},_,#{?#{==:#{window_index},2},▀,￭}}\
#{?#{<:#{session_windows},3},_,#{?#{==:#{window_index},3},▀,￭}}\
#{?#{<:#{session_windows},4},_,#{?#{==:#{window_index},4},▀,￭}}\
#{?#{<:#{session_windows},5},_,#{?#{==:#{window_index},5},▀,￭}}\
#{?#{<:#{session_windows},6},_,#{?#{==:#{window_index},6},▀,￭}}\
#{?#{<:#{session_windows},7},_,#{?#{==:#{window_index},7},▀,￭}}\
#{?#{<:#{session_windows},8},_,#{?#{==:#{window_index},8},▀,￭}}\
#{?#{<:#{session_windows},9},_,#{?#{==:#{window_index},9},▀,￭}}\
 \
#[fg=black,bg=black]\
#{E:##{p#{#{e|-:#{client_width},11}:#}}}\
"
set-hook -g window-unlinked {
	if -F "#{e|>:#{session_attached},0}" {display "#{E:@desks}"}
}

# Lift desk to new position
bind -n M-\{ {
	if -F "#{window_start_flag}" {} {swap-window -d -t "{previous}"}
	display "#{E:@desks}"
}
bind -n M-\} {
	if -F "#{window_end_flag}" {
		if -F "#{e|<:#{session_windows},9}" {new-window -bd}
	} {swap-window -d -t "{next}"; display "#{E:@desks}"}
	 display "#{E:@desks}"
}

# Desk jump
bind -n M-, {
	if -F "#{window_start_flag}" {if -F "#{e|!=:#{window_index},1}" {new-window -b}} {previous-window}
	display "#{E:@desks}"
}
bind -n M-. {
	if -F "#{window_end_flag}" {if -F "#{e|<:#{session_windows},9}" {new-window -a}} {next-window}
	display "#{E:@desks}"
}
bind -n S-M-WheelUpPane {
	if -F "#{window_end_flag}" {if -F "#{e|<:#{session_windows},9}" {new-window -a}} {next-window}
	display "#{E:@desks}"
}
bind -n S-M-WheelDownPane {
	if -F "#{window_start_flag}" {if -F "#{e|!=:#{window_index},1}" {new-window -b}} {previous-window}
	display "#{E:@desks}"
}
# Alternative desk jump for unshifted Lift desk keys
bind -n M-[ {
	if -F "#{window_start_flag}" {if -F "#{e|!=:#{window_index},1}" {new-window -b}} {previous-window}
	display "#{E:@desks}"
}
bind -n M-] {
	if -F "#{window_end_flag}" {if -F "#{e|<:#{session_windows},9}" {new-window -a}} {next-window}
	display "#{E:@desks}"
}

# Yank pane across desks
bind -n M-> {
	select-pane -m
	if -F "#{window_end_flag}" {if -F "#{e|<:#{session_windows},9}" {new-window -a}} {next-window}
	select-pane -t "{bottom-right}"
	if -F "#{pane_at_left}" {
		join-pane -h -l 60% -s "{marked}" -t "{bottom-right}"
	} {
		if -F "#{e|<:#{pane_height},5}" {
			resize-pane -y 5
		}
		join-pane -l 75% -s "{marked}" -t "{bottom}"
	}
	display "#{E:@desks}"
}
bind -n M-< {
	select-pane -m
	if -F "#{window_start_flag}" {if -F "#{e|!=:#{window_index},1}" {new-window -b}} {previous-window}
	select-pane -t "{bottom-right}"
	if -F "#{pane_at_left}" {
		join-pane -h -l 60% -s "{marked}" -t "{bottom-right}"
	} {
		if -F "#{e|<:#{pane_height},5}" {
			resize-pane -y 5
		}
		join-pane -l 75% -s "{marked}" -t "{bottom}"
	}
	display "#{E:@desks}"
}

# Desktop direct jumping
bind -n M-1 {
	select-window -t 1
	display "#{E:@desks}"
}
bind -n M-2 {
	if -F "#{e|<:#{session_windows},2}" {select-window -t "{end}" ; new-window}
	select-window -t 2
	display "#{E:@desks}"
}
bind -n M-3 {
	if -F "#{e|<:#{session_windows},3}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},3}" {select-window -t "{end}" ; new-window}
	select-window -t 3
	display "#{E:@desks}"
}
bind -n M-4 {
	if -F "#{e|<:#{session_windows},4}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},4}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},4}" {select-window -t "{end}" ; new-window}
	select-window -t 4
	display "#{E:@desks}"
}
bind -n M-5 {
	if -F "#{e|<:#{session_windows},5}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},5}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},5}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},5}" {select-window -t "{end}" ; new-window}
	select-window -t 5
	display "#{E:@desks}"
}
bind -n M-6 {
	if -F "#{e|<:#{session_windows},6}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},6}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},6}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},6}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},6}" {select-window -t "{end}" ; new-window}
	select-window -t 6
	display "#{E:@desks}"
}
bind -n M-7 {
	if -F "#{e|<:#{session_windows},7}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},7}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},7}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},7}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},7}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},7}" {select-window -t "{end}" ; new-window}
	select-window -t 7
	display "#{E:@desks}"
}
bind -n M-8 {
	if -F "#{e|<:#{session_windows},8}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},8}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},8}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},8}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},8}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},8}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},8}" {select-window -t "{end}" ; new-window}
	select-window -t 8
	display "#{E:@desks}"
}
bind -n M-9 {
	if -F "#{e|<:#{session_windows},9}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},9}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},9}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},9}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},9}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},9}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},9}" {select-window -t "{end}" ; new-window}
	if -F "#{e|<:#{session_windows},9}" {select-window -t "{end}" ; new-window}
	select-window -t 9
	display "#{E:@desks}"
}


# Navigation
bind -n MouseDown1Pane select-pane -t = ";" send-keys -M
bind -n -N"Nav left"  M-Left  if -F "#{pane_at_left}" {} {select-pane -L}
bind -n -N"Nav right" M-Right if -F "#{pane_at_right}" {} {select-pane -R}
bind -n -N"Nav up"    M-Up    if -F "#{pane_at_top}" {} {select-pane -U}
bind -n -N"Nav down"  M-Down  if -F "#{pane_at_bottom}" {} {select-pane -D}
bind -n -N"Tab swap"  M-Tab  select-pane -t "{last}"
bind -n M-WheelUpPane select-pane -t "{previous}"
bind -n M-WheelDownPane select-pane -t "{next}"
# Legacy control sequences
bind -n -N"Nav left"  C-Left  if -F "#{pane_at_left}" {} {select-pane -L}
bind -n -N"Nav right" C-Right if -F "#{pane_at_right}" {} {select-pane -R}
bind -n -N"Nav up"    C-Up    if -F "#{pane_at_top}" {} {select-pane -U}
bind -n -N"Nav down"  C-Down  if -F "#{pane_at_bottom}" {} {select-pane -D}
bind -n -N"Tab swap"  C-Tab  select-pane -t "{last}"


# Launch new space
bind -n -N"Launch space" M-Space {
	if -F "#{pane_at_left}" {
		select-pane -t "{bottom-right}"
		if -F "#{pane_at_left}" {
			split-window -h -l 60% -c "#{pane_current_path}"
		} {
			if -F "#{e|<:#{pane_height},5}" {
				resize-pane -y 5
			}
			split-window -l 75% -t"{bottom-right}" -c "#{pane_current_path}"
		}
	} {
			if -F "#{e|<:#{pane_height},5}" {
				resize-pane -y 5
			}
			split-window -l 75% -c "#{pane_current_path}"
	}
}
bind -n -N"Launch space" M-: {
	select-pane -t "{bottom-left}"
	split-window -b -l 1 -f -c "#{pane_current_path}"
}

# Layout
bind -n MouseDrag1Border resize-pane -M
bind -n M-\; resize-pane -Z
bind -n M-\' resize-pane -Z
bind -n M-Enter resize-pane -Z
bind -n M-BSpace kill-pane
