[packages]
  [packages.cli]
  command_line_shell = "bash"
  text_editor = "micro"
  text_editor_modal = "helix"
  file_manager = "nnn"

  [packages.gui]
  terminal = "alacritty"
  browser = "firefox"
