[packages]
  [packages.cli]
  command_line_shell = "bash"
  text_editor = "micro"
  text_editor_modal = "helix"
  file_manager = "nnn"
  search = "ripgrep"
  font = "NotoMono Nerd Font"
  launcher = "fzf"

  [packages.gui]
  terminal = "alacritty"
  browser = "firefox"
  launcher = "fzf"
